// Offline generation only; H owns the default output src/ynab/types.ts.
import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

if (process.argv.length > 3) throw new Error('Usage: node scripts/generate-types.mjs [output.ts]');
const snapshot = new URL('../docs/reference/ynab-openapi-1.87.0.yaml', import.meta.url);
const expected = '69411d596ee4b6f79720615038ac9cdfea43875013ca9d0e5d235ba505ebf26f';
const source = await readFile(snapshot, 'utf8');
if (createHash('sha256').update(source).digest('hex') !== expected) {
  throw new Error('Pinned OpenAPI snapshot SHA-256 mismatch');
}
// The pinned snapshot has only local references. Do not enable remote resolution.
for (const line of source.split('\n')) {
  if (/\$ref:/.test(line) && !/\$ref:\s*['"]?#\//.test(line)) {
    throw new Error('OpenAPI generation requires local references');
  }
}
const output = process.argv[2] ?? fileURLToPath(new URL('../src/ynab/types.ts', import.meta.url));
const ast = await openapiTS(source, { alphabetize: true });
const header = `// Generated by openapi-typescript 7.10.1; do not edit.\n// YNAB 1.87.0 SHA-256: ${expected}\n`;
await mkdir(dirname(output), { recursive: true });
await writeFile(output, header + astToString(ast), 'utf8');
